[greeter]
background = #0a120e
theme-name = Adwaita-dark
icon-theme-name = Adwaita
font-name = JetBrainsMono Nerd Font 11
xft-antialias = true
xft-hintstyle = hintslight
indicators =
position = 50%,center 50%,center
hide-user-image = true
