# Backend

backend = "glx";
#backend = "xrender";
vsync = true;

# Corners
corner-radius =0;
rounded-corners-exclude = [
  "class_g = 'Alacritty'",
  "window_type = 'dock'",
  "window_type = 'desktop'"
];


# Transparency
inactive-opacity = 0.90;
active-opacity = 1.00;
frame-opacity = 1.00;

# Rules
opacity-rule = [
  "100:class_g = 'firefox'",
];
