- name: Copy greetd config
  become: true
  ansible.builtin.copy:
    src: "{{ dotfiles_root }}/system/greetd/config.toml"
    dest: "/etc/greetd/config.toml"
    owner: root
    group: root
    mode: "0644"
